@TaskManager_HostAddress = http://localhost:5235

GET {{TaskManager_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{TaskManager_HostAddress}}/api/tasks/ 
Accept: application/json

###
GET {{TaskManager_HostAddress}}/api/tasks/1
Accept: application/json

###
POST {{TaskManager_HostAddress}}/api/tasks
Content-Type: application/json
{
  "title": "Read Book",
  "description": "Head First Design Patterns",
  "state": 0
}

###
PUT {{TaskManager_HostAddress}}/api/tasks/1
Content-Type: application/json
{
  "id": 1,
  "title": "Changed",
  "description": "Changed",
  "state": 0
}

###
DELETE {{TaskManager_HostAddress}}/api/tasks/1
Accept: application/json

###
GET {{TaskManager_HostAddress}}/api/jobs
Accept: application/json

###
GET {{TaskManager_HostAddress}}/api/jobs/1
Accept: application/json

###
POST {{TaskManager_HostAddress}}/api/jobs
Content-Type: application/json
{ 
  "company": "Amazon",
  "status": 1,
  "interviewRound": 2
}

###
PUT {{TaskManager_HostAddress}}/api/jobs/1
Content-Type: application/json
{
  "id": 1,
  "company": "NDA",
  "status": 0,
  "interviewRound": 0
}

###
DELETE {{TaskManager_HostAddress}}/api/jobs/1
Accept: application/json
