@JobsWebScraper_HostAddress = http://localhost:5235

###
GET {{JobsWebScraper_HostAddress}}/api/tasks/ 
Accept: application/json

###
GET {{JobsWebScraper_HostAddress}}/api/tasks/2
Accept: application/json

###
POST {{JobsWebScraper_HostAddress}}/api/tasks
Content-Type: application/json
{
  "title": "Read Book",
  "description": "Head First Design Patterns",
  "state": 0
}

###
PUT {{JobsWebScraper_HostAddress}}/api/tasks/2
Content-Type: application/json
{
  "title": "Changed",
  "description": "Changed",
  "state": 0
}

###
DELETE {{JobsWebScraper_HostAddress}}/api/tasks/4
Accept: application/json

###
GET {{JobsWebScraper_HostAddress}}/api/jobs
Accept: application/json

###
GET {{JobsWebScraper_HostAddress}}/api/jobs/2
Accept: application/json

###
POST {{JobsWebScraper_HostAddress}}/api/jobs
Content-Type: application/json
{ 
  "company": "Amazon",
  "status": 1,
  "interviewRound": 2
}

###
PUT {{JobsWebScraper_HostAddress}}/api/jobs/5
Content-Type: application/json
{
  "id": 1,
  "company": "NDA",
  "status": 0,
  "interviewRound": 0
}

###
DELETE {{JobsWebScraper_HostAddress}}/api/jobs/5
Accept: application/json

###
POST {{JobsWebScraper_HostAddress}}/api/automation
Content-Type: application/json